add api ingress
overture-stack/helm-charts pull request #40
Opened 2020-04-14 19:45 UTC by henro001

2020-04-20 20:24 UTC, rtisma approved these changes

2020-04-20 21:35 UTC, rtisma requested changes

2020-04-20 21:35 UTC, rtisma commented on ego/Chart.yaml
> +>>>>>>> master
im assuming you still want 1.0.0. So delete these selected lines

2020-04-20 21:35 UTC, rtisma commented on ego/Chart.yaml
> +<<<<<<< HEAD
delete this line

2020-04-20 21:42 UTC, rtisma approved these changes

2020-04-21 16:29 UTC, andricDu approved these changes

2020-04-21 16:43 UTC, merged